import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir, readFile } from 'node:fs/promises';

await mkdir('.cache', { recursive: true });
const browser = await chromium.launch({ headless: true });
const url = process.env.TEST_URL || 'http://localhost:5174';
const metadata = JSON.parse(await readFile('resources/ui-icons/catalog.json', 'utf8'));
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, colorScheme: 'light', permissions: ['clipboard-read', 'clipboard-write'] });
const page = await context.newPage();
const errors = [];
const requests = [];
page.on('pageerror', error => errors.push(error.message));
page.on('request', request => requests.push(request.url()));
const noOverflow = async () => assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
try {
  await page.goto(url);
  await page.locator('[data-donate="clay"]').check();
  await page.locator('#hide-donated').check();
  await page.locator('#auto-collapse').check();
  await page.locator('#toggle-theme').click();
  assert.equal(requests.some(request => request.includes('previews.json')), false);
  await page.locator('.nav-group summary').click();
  await page.getByRole('link', { name: /Icon Browser/ }).click();
  await page.locator('#rows tr').first().waitFor();
  assert.equal(new URL(page.url()).pathname, '/modding/tools/icon-browser/');
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark');
  assert.equal(await page.locator('#total').innerText(), '9,788');
  assert.equal(await page.locator('#rows tr').count(), 80);
  assert.equal(await page.locator('.nav-dropdown a').getAttribute('aria-current'), 'page');
  await page.screenshot({ path: '.cache/icons-dark-table.png' });
  await page.locator('#next').click();
  assert.match(await page.locator('#page-label').innerText(), /Page 2 of/);
  await page.locator('#page-size').selectOption('40');
  assert.equal(await page.locator('#rows tr').count(), 40);
  assert.match(await page.locator('#page-label').innerText(), /Page 1 of/);

  await page.locator('#query').fill('outline');
  assert.ok(await page.locator('#rows .icon-name').count() > 0);
  await page.locator('#hide-outlines').check();
  assert.equal(await page.locator('#icon-results').innerText(), '0 matching sprites');
  assert.equal(await page.locator('#next').isDisabled(), true);
  await page.locator('#reset-icons').click();
  assert.equal(await page.locator('#hide-outlines').isChecked(), true);
  assert.match(await page.locator('#icon-results').innerText(), /6,464 sprites/);
  await page.locator('#next').click();
  assert.ok((await page.locator('#rows .icon-name').allTextContents()).every(name => !name.includes('outline')));
  await page.reload();
  await page.locator('#rows tr').first().waitFor();
  assert.equal(await page.locator('#hide-outlines').isChecked(), true);
  assert.match(await page.locator('#icon-results').innerText(), /6,464 sprites/);
  await page.locator('#grid-view').click();
  await page.locator('#query').fill('outline');
  assert.equal(await page.locator('.icon-card').count(), 0);
  await page.locator('#hide-outlines').uncheck();
  assert.ok(await page.locator('.icon-card').count() > 0);
  await page.locator('#reset-icons').click();
  await page.locator('#table-view').click();
  await page.locator('#page-size').selectOption('40');

  const sample = metadata.icons.find(icon => icon.compact && icon.name.includes('heart'));
  await page.locator('#query').fill(sample.name);
  await page.locator('#category').selectOption(sample.category);
  await page.locator('#compact').check();
  const expected = metadata.icons.filter(icon => icon.compact && icon.category === sample.category && icon.name.includes(sample.name));
  assert.equal(await page.locator('#rows tr').count(), expected.length);
  await page.getByRole('button', { name: `Copy markup for ${sample.name}`, exact: true }).click();
  assert.equal(await page.evaluate(() => navigator.clipboard.readText()), sample.markup);
  await page.evaluate(() => Object.defineProperty(navigator, 'clipboard', { configurable: true, value: undefined }));
  await page.getByRole('button', { name: `Copy markup for ${sample.name}`, exact: true }).click();
  assert.equal(await page.locator('#copy-dialog').isVisible(), true);
  assert.equal(await page.locator('#copy-text').inputValue(), sample.markup);
  assert.equal(await page.locator('#copy-text').evaluate(input => input.selectionEnd - input.selectionStart), sample.markup.length);
  await page.locator('#close-dialog').click();
  await page.locator('#query').fill('no_such_sprite_zzzz');
  assert.match(await page.locator('#rows').innerText(), /No matching sprites/);
  assert.equal(await page.locator('#next').isDisabled(), true);
  await page.locator('#reset-icons').click();
  await page.locator('#grid-view').click();
  assert.equal(await page.locator('.icon-card').count(), 40);
  await page.reload();
  await page.locator('.icon-card').first().waitFor();
  assert.equal(await page.locator('#grid-view').getAttribute('aria-pressed'), 'true');
  await page.locator('#query').fill('heart');
  await page.screenshot({ path: '.cache/icons-dark-grid.png' });
  await page.locator('#toggle-theme').click();
  await page.screenshot({ path: '.cache/icons-light-grid.png' });
  await noOverflow();
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.screenshot({ path: '.cache/icons-mobile.png' });
  await page.locator('#table-view').click();
  await noOverflow();
  await page.locator('.nav-group summary').focus();
  await page.keyboard.press('Enter');
  assert.equal(await page.locator('.nav-group').getAttribute('open'), '');
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('.nav-group').getAttribute('open'), null);
  await page.screenshot({ path: '.cache/icons-mobile-table.png' });

  await page.getByRole('link', { name: 'Museum', exact: true }).click();
  await page.locator('#hide-donated').waitFor();
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'light');
  assert.equal(await page.locator('#hide-donated').isChecked(), true);
  assert.equal(await page.locator('#auto-collapse').isChecked(), true);
  await page.locator('#hide-donated').uncheck();
  assert.equal(await page.locator('[data-donate="clay"]').isChecked(), true);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.screenshot({ path: '.cache/shared-museum.png' });

  const unavailable = await browser.newContext();
  const failedPage = await unavailable.newPage();
  await failedPage.route('**/previews.json', route => route.fulfill({ status: 503, body: 'Unavailable' }));
  await failedPage.goto(`${url}/modding/tools/icon-browser/`);
  await failedPage.locator('#load-error').waitFor();
  assert.equal(await failedPage.locator('#query').isDisabled(), true);
  await failedPage.unroute('**/previews.json');
  await failedPage.locator('#retry-icons').click();
  await failedPage.locator('#rows tr').first().waitFor();
  assert.equal(await failedPage.locator('#rows tr').count(), 80);
  await unavailable.close();

  const noStorage = await browser.newContext({ colorScheme: 'dark' });
  await noStorage.addInitScript(() => Object.defineProperty(window, 'localStorage', { get() { throw new Error('Storage blocked'); } }));
  const isolated = await noStorage.newPage();
  await isolated.goto(`${url}/modding/tools/icon-browser/`);
  await isolated.locator('#rows tr').first().waitFor();
  assert.equal(await isolated.locator('html').getAttribute('data-theme'), 'dark');
  await isolated.locator('#toggle-theme').click();
  assert.equal(await isolated.locator('html').getAttribute('data-theme'), 'light');
  await noStorage.close();
  assert.deepEqual(errors, []);
  console.log('Icon Browser checks passed: shared navigation/theme, preserved museum progress, lazy catalog, filters, pagination, table/grid persistence, clipboard/fallback, saved outline setting, keyboard/mobile layout, load retry, and blocked storage.');
} finally { await browser.close(); }
