import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const browser = await chromium.launch({ headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, colorScheme: 'light' });
await context.addInitScript(() => {
  if (!localStorage.getItem('mistria-museum-progress-v1')) localStorage.setItem('mistria-museum-progress-v1', JSON.stringify({ app: 'mistria-museum-tracker', version: 1, progress: { koi: {status:'collected', notes:'old note retained in backup'} } }));
});
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
try {
  await page.goto(process.env.TEST_URL || 'http://localhost:5174');
  assert.equal(await page.locator('#title').innerText(), 'Finish your Museum');
  assert.doesNotMatch(await page.locator('body').innerText(), /A little closer|Find your next donation|Combine filters to plan/);
  assert.equal(await page.locator('link[rel="icon"]').getAttribute('href'), '/adeline.png');
  const served = await page.request.get(new URL('/adeline.png', page.url()).href);
  assert.deepEqual(await served.body(), await readFile('public/adeline.png'));
  const sprite = await page.locator('.brand img').evaluate(img => ({ width:img.naturalWidth,height:img.naturalHeight }));
  assert.deepEqual(sprite, {width:24,height:20});
  await page.locator('[data-layout="table"]').click();
  assert.equal(await page.locator('.museum-row').count(),409);
  assert.equal(await page.locator('.item-card').count(),0);
  await page.locator('[data-wing="Fish"]').click();
  await page.locator('[data-filter="seasons"][value="Spring"]').check();
  await page.locator('[data-filter="weather"][value="Rain"]').check();
  assert.equal(await page.locator('[data-id="bluegill"]').count(),0);
  assert.equal(await page.locator('[data-id="walleye"]').count(),1);
  await page.locator('[data-filter="weather"][value="Any Weather"]').check();
  assert.equal(await page.locator('[data-id="bluegill"]').count(),1);
  await page.locator('[data-filter="weather"][value="Rain"]').uncheck();
  assert.equal(await page.locator('[data-id="walleye"]').count(),0);
  await page.locator('[data-filter="seasons"][value="All Seasons"]').check();
  assert.equal(await page.locator('[data-donate="koi"]').isChecked(),false);
  await page.locator('[data-details="koi"]').click();
  assert.match(await page.locator('#details-koi').innerText(), /Medium/);
  assert.equal(await page.locator('[data-notes], [data-status]').count(),0);
  assert.doesNotMatch(await page.locator('#details-koi').innerText(), /Your notes|Collection status|old note/);
  await page.locator('[data-donate="koi"]').check();
  await page.locator('[data-layout="cards"]').click();
  assert.equal(await page.locator('[data-donate="koi"]').isChecked(),true);
  await page.locator('[data-layout="table"]').click();
  await page.reload();
  assert.equal(await page.locator('[data-layout="table"]').getAttribute('aria-pressed'),'true');
  assert.equal(await page.locator('[data-donate="koi"]').isChecked(),true);
  await page.locator('#search').fill('koi');
  await page.locator('#hide-donated').check();
  assert.equal(await page.locator('[data-id="koi"]').count(),0);
  await page.locator('#hide-donated').uncheck();
  await page.locator('#reset').click();
  await page.locator('#auto-collapse').check();
  for (const id of ['clay','peat','shard-mass','shards','sod']) await page.locator(`[data-donate="${id}"]`).click();
  const set = page.locator('[data-toggle-set="Archaeology:Dig Site Material Set"]');
  assert.equal(await set.getAttribute('aria-expanded'),'false');
  await set.click();
  assert.equal(await page.locator('[data-donate="clay"]').isVisible(),true);
  await page.locator('#collapse-sets').click();
  assert.equal(await page.locator('.set-table[hidden]').count(),82);
  await page.locator('#expand-sets').click();
  await page.locator('[data-wing="Fish"]').click();
  await page.locator('[data-details="koi"]').click();
  await page.screenshot({animations:'disabled',path:'.cache/museum-table-light.png'});
  await page.locator('#toggle-theme').click();
  await page.screenshot({animations:'disabled',path:'.cache/museum-table-dark.png'});
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth),false);
  assert.equal(await page.locator('.table-scroll').first().evaluate(el => el.scrollWidth > el.clientWidth),true);
  await page.screenshot({animations:'disabled',path:'.cache/museum-table-mobile.png'});
  assert.deepEqual(errors,[]);
  console.log('Museum layout checks passed: exact sprite, simplified copy, separate Any Weather, legacy progress, table/card persistence, details, donation/collapse behavior, dark mode and mobile scrolling.');
} finally { await browser.close(); }
